### PR TITLE
fix: updated confluence to 8.9.4 from 8.9.3

### PR DESCRIPTION
**Pull request by JoeHCQ1**

### CODE REVIEW

**Review by corang — DISMISSED** [review]

**Comment by anthonywendt** [comment]
Is there a reason we are only updating images and not the chart as well?

**Comment by JoeHCQ1** [comment]
@anthonywendt no reason except this PR exists as I broke a larger PR out into smaller pieces, and that's all I did in the larger PR.

**Comment by JoeHCQ1** [comment]
@anthonywendt I just updated the chart

**Review by anthonywendt — APPROVED** [review]
LGTM

Although the versioning on this uds-package seems weird. Usually the version matches the version of the application, not the chart which are different in this case. That can be handled in a separate issue

**Pull request merged**
